version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: "pokemon.db"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensordb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./tmp/db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  service-a:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.service-a
    restart: always
    environment:
      - FREQUENCY=1
      - SENSOR_TYPE=temp
    depends_on:
      - service-b
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    expose:
      - "8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service-a.rule=Host(`service-a.docker.localhost`)"
      # - "traefik.http.routers.service-a.rule=PathPrefix(`/service-a`)"
      - "traefik.http.services.service-a.loadbalancer.server.port=8081"

  service-b:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.service-b
    restart: always
    ports:
      - "8082:8082"
      - "50051:50051"
    expose:
      - "8082"
      - "50051"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
