version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: "pokemon.db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensordb
    ports:
      - "3306:3306"
    expose:
      - "3306"
