version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: "pokemon.db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensordb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db-data1:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  service-a:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.service-a
    restart: always
    ports:
      - "8081:8081"
    environment:
      - FREQUENCY=1000
    depends_on:
      - service-b

  service-b:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.service-b
    restart: always
    ports:
      - "8082:8082"
      - "50051:50051"
    expose:
      - "8082"
      - "50051"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql


volumes:
  db-data1: